--- #YAML:1.0
name:                POSIX-strptime
version:             0.08
abstract:            Perl extension to the POSIX date parsing strptime(3) function
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Philippe M. Chiasson <gozer@cpan.org>
